"""Authenticated GlitchTip and selected Discord Gateway employee ingress."""

import hashlib
import hmac
import json
from datetime import UTC, datetime
from typing import Any
from uuid import UUID

from anyio import from_thread
from fastapi import APIRouter, Depends, HTTPException, Request
from sqlalchemy.orm import Session

from preloop.models.crud import crud_flow
from preloop.models.db.session import _safe_close_db_session, get_db_session
from preloop.services.employee_events import (
    EmployeeEventDenied,
    MAX_EVENT_BYTES,
    ingest_employee_event,
)

router = APIRouter(prefix="/employee-events", tags=["Employee events"])


async def _read_employee_body(request: Request) -> bytes:
    """Read an event body, refusing it once it passes the event limit."""
    length = request.headers.get("content-length")
    if length and (not length.isdigit() or int(length) > MAX_EVENT_BYTES):
        raise HTTPException(413, "Event payload is too large")
    chunks = bytearray()
    async for chunk in request.stream():
        chunks.extend(chunk)
        if len(chunks) > MAX_EVENT_BYTES:
            raise HTTPException(413, "Event payload is too large")
    return bytes(chunks)


async def _ingest_on_loop(
    *,
    account_id: Any,
    flow_id: UUID,
    source: Any,
    connection_id: Any,
    event_id: Any,
    subject: Any,
    kind: Any,
    payload: Any,
    occurred_at: datetime,
) -> Any:
    """Open a session on this loop thread and hand the event to intake.

    The request handler is synchronous, so its authentication session stays
    on the worker thread. Intake reloads the flow on a session created here.
    """
    db = next(get_db_session())
    try:
        return await ingest_employee_event(
            db,
            account_id=account_id,
            flow_id=flow_id,
            source=source,
            connection_id=connection_id,
            event_id=event_id,
            subject=subject,
            kind=kind,
            payload=payload,
            occurred_at=occurred_at,
        )
    finally:
        _safe_close_db_session(db)


@router.post("/{flow_id}")
def receive_employee_event(
    flow_id: UUID,
    request: Request,
    db: Session = Depends(get_db_session),
) -> dict[str, str | bool]:
    """Verify raw-body HMAC before translating a configured source event.

    GlitchTip uses X-Sentry-Hook-Signature. Discord Gateway bridges use
    X-Preloop-Signature (hex HMAC-SHA256). The secret is generated by the
    account owner and stored in the existing Flow webhook configuration.
    The handler is synchronous so that checkout stays off the event loop.
    The body stream and execution dispatch run on the loop.
    """
    body = from_thread.run(_read_employee_body, request)
    flow = crud_flow.get(db, id=str(flow_id), refresh=True)
    config = (flow.webhook_config or {}) if flow else {}
    binding = ((flow.trigger_config or {}).get("employee_events", {})) if flow else {}
    secret = config.get("employee_secret")
    signature = (
        request.headers.get("x-sentry-hook-signature")
        if binding.get("source") == "glitchtip"
        else request.headers.get("x-preloop-signature")
    )
    if (
        not isinstance(secret, str)
        or len(secret) < 32
        or not signature
        or not hmac.compare_digest(
            hmac.new(secret.encode(), body, hashlib.sha256).hexdigest(), signature
        )
    ):
        raise HTTPException(401, "Invalid event authentication")
    try:
        data = json.loads(body)
        if not isinstance(data, dict):
            raise EmployeeEventDenied("Event must be an object")
        source = binding.get("source")
        if source == "glitchtip":
            event = data.get("data", {}).get("event", {})
            project = data.get("data", {}).get("project", {})
            event_id = event.get("event_id") or event.get("id")
            subject = f"project:{project.get('id')}:issue:{event.get('issue_id') or event.get('group_id')}"
            kind = "error"
            payload = data
        elif source == "discord":
            event_id, subject, kind = (
                data.get("event_id"),
                data.get("subject"),
                data.get("kind"),
            )
            payload = data.get("payload")
        else:
            raise EmployeeEventDenied("Source does not support this ingress")

        async def dispatch() -> Any:
            return await _ingest_on_loop(
                account_id=flow.account_id,
                flow_id=flow_id,
                source=source,
                connection_id=binding.get("connection_id"),
                event_id=event_id,
                subject=subject,
                kind=kind,
                payload=payload,
                occurred_at=datetime.now(UTC),
            )

        # from_thread.run accepts only positional arguments.
        receipt = from_thread.run(dispatch)
    except (ValueError, TypeError, AttributeError) as exc:
        raise HTTPException(422, "Event does not match the configured scope") from exc
    return {
        "execution_id": receipt.execution_id,
        "status": receipt.status,
        "duplicate": receipt.duplicate,
    }
